# Set the default shell to ZSH
set-option -g default-shell /usr/bin/zsh

# Enable colorful terminal
set -g default-terminal "screen-256color"

# Remap prefix from 'C-b' to 'C-a' and 'C-Space'
set -g prefix  C-a
set -g prefix2 C-space
bind C-a send-prefix
bind C-space send-prefix

set -g mouse on

# Split panes using v and h keys
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

# Disable automatic renaming
set-option -wg automatic-rename off

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf has been reloaded."

# Switch panes using Meta + vim-motion
bind -n M-H select-pane -L
bind -n M-L select-pane -R
bind -n M-J select-pane -U
bind -n M-K select-pane -D

# Prevent ESC+l acting like M-l
# See: https://unix.stackexchange.com/questions/23138
set -s escape-time 0

# Resize panes using Meta + vim-motion
bind M-H resize-pane -L 2
bind M-J resize-pane -D 2
bind M-K resize-pane -U 2
bind M-L resize-pane -L 2

# Make an empty line above the status bar
set -Fg 'status-format[1]' "#{status-format[0]}"
set -g status-format[0] ""
set -g status 2

# Format the status bar
set -g status-justify centre
set -g status-style bg=default
set -g status-right "%A %d-%m-%Y %H:%M"
set -g status-left "#H [#S]"
set -g status-interval 60
set -g status-left-length 50
set -g window-status-format "#[fg=white]#I:#W#{?window_zoomed_flag,+, } "
# The '+' sign indicates a window with zoomed pane
set -g window-status-current-format "#[fg=green,bold]#I:#W#{?window_zoomed_flag,+, } "

