# Set the default shell to ZSH
set-option -g default-shell /usr/bin/zsh

# Enable colorful terminal
set -g default-terminal "screen-256color"

# Remap prefix from 'C-b' to 'C-a'
set-option -g prefix C-a

set -g mouse on

# Split panes using v and h keys
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

# Disable automatic renaming
set-option -wg automatic-rename off

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf \; display-message "tmux.conf has been reloaded."

# Switch panes using Meta + vim-motion
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

# Resize panes using Meta + vim-motion
bind -n M-H resize-pane -L 2
bind -n M-J resize-pane -D 2
bind -n M-K resize-pane -U 2
bind -n M-L resize-pane -L 2

# Make an empty line above the status bar
set -Fg 'status-format[1]' "#{status-format[0]}"
set -g status-format[0] ""
set -g status 2

# Format the status bar
set -g status-justify centre
set -g status-style bg=default
set -g status-right "%A %d-%m-%Y %H:%M"
set -g status-left "#H [#S]"
set -g status-interval 60
set -g status-left-length 50
set -g window-status-format "(#[fg=white]#I:#W)"
set -g window-status-current-format "#[fg=green,bold](#I:#W)"

