- name: Ensure required packages are installed
  package:
    name:
      - git
      - curl
    state: present

- name: Clone fzf repository
  become: false
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.local/src/fzf
    version: master

- name: Install fzf
  become: false
  command: ./install --no-zsh
  args:
    chdir: ~/.local/src/fzf
  register: fzf_install
  no_log: false
  async: 0
  poll: 0
