# -----------------------------------------------------------------------------
# ZSH SETUP
# -----------------------------------------------------------------------------

- name: Ensure zsh is installed
  become: yes
  package:
    name: zsh
    state: present

# -----------------------------------------------------------------------------
# INSTALL OH-MY-ZSH
# -----------------------------------------------------------------------------

- name: Check if Oh-My-Zsh is installed
  stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: ohmyzsh_dir
  become: false

- name: Install Oh-My-Zsh
  become: false
  shell: |
    RUNZSH=no CHSH=no sh -c \
      "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
  when: not ohmyzsh_dir.stat.exists

- name: Set Zsh as default shell
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh


# -----------------------------------------------------------------------------
# INSTALL THEME
# -----------------------------------------------------------------------------

- name: Install Zsh theme
  become: false
  git:
    repo: "{{ zsh_theme.repo }}"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/{{ zsh_theme.name }}"
    depth: 1
  when: zsh_theme.repo is defined

- name: Deploy theme config
  become: false
  copy:
    src: "{{ zsh_theme.config_file }}"
    dest: "{{ home_dir }}/.p10k.zsh"
    mode: '0644'
  when: zsh_theme.config_file is defined

# -----------------------------------------------------------------------------
# PLUGINS
# -----------------------------------------------------------------------------

- name: Ensure plugin directory exists
  become: false
  file:
    path: "{{ home_dir }}/.oh-my-zsh/custom/plugins"
    state: directory
    mode: '0755'

- name: Install external Zsh plugins
  become: false
  git:
    repo: "{{ item.repo }}"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
  loop: "{{ zsh_plugins }}"
  when: item.repo is defined

# -----------------------------------------------------------------------------
